/**
 * Rooms of building A1 mirrored from the classroom floor plan (client/src/mock/campusBuildingData.js)
 * so the Room List (UC-2.2) shows the same rooms as the floor plan.
 * Codes already used by core seed rooms are skipped; duplicate plan codes get a floor suffix.
 * room_type values match ROOM_TYPES (lecture | lab | office | warehouse).
 */
export const FLOOR_PLAN_ROOMS = [
  { code: "A1-PH-TB", name: "PH (Phòng Học & Tự Học)", floor: 1, room_type: "lecture", capacity: 65, area: 95 },
  { code: "A1-PTV", name: "PTV (Phòng Thư Viện)", floor: 1, room_type: "lecture", capacity: 250, area: 360 },
  { code: "A1-K1", name: "Kho 1", floor: 1, room_type: "warehouse", capacity: 0, area: 32 },
  { code: "A1-K2", name: "Kho 2", floor: 1, room_type: "warehouse", capacity: 0, area: 32 },
  { code: "A1-PTH2", name: "PTH 2 (Phòng Tự Học Lớn)", floor: 1, room_type: "lecture", capacity: 120, area: 180 },
  { code: "A1-KHO-TAY", name: "Kho Phụ", floor: 1, room_type: "warehouse", capacity: 0, area: 25 },
  { code: "A1-CV", name: "Sân Cổng Vào (CV)", floor: 1, room_type: "lecture", capacity: 150, area: 220 },
  { code: "A1-WC-NAM", name: "NVS Nam (WC)", floor: 1, room_type: "warehouse", capacity: 0, area: 25 },
  { code: "A1-WC-NU", name: "NVS Nữ (WC)", floor: 1, room_type: "warehouse", capacity: 0, area: 25 },
  { code: "A1-PH-DN", name: "PH (Phòng Học Lớn)", floor: 1, room_type: "lecture", capacity: 120, area: 180 },
  { code: "A1-202", name: "PH 202", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-203", name: "PH 203", floor: 2, room_type: "lab", capacity: 60, area: 75 },
  { code: "A1-207", name: "PH 207", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-208", name: "PH 208", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-209", name: "PH 209", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-210", name: "PH 210", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-211", name: "PH 211", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-212", name: "PH 212", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-NC-01", name: "Phòng Nghiên Cứu 1", floor: 2, room_type: "office", capacity: 45, area: 160 },
  { code: "A1-WC-NU-T2", name: "NVS Nữ", floor: 2, room_type: "warehouse", capacity: 0, area: 25 },
  { code: "A1-204", name: "PH 204", floor: 2, room_type: "lab", capacity: 60, area: 75 },
  { code: "A1-205", name: "PH 205", floor: 2, room_type: "office", capacity: 50, area: 65 },
  { code: "A1-206", name: "PH 206", floor: 2, room_type: "office", capacity: 50, area: 65 },
  { code: "A1-215", name: "PH 215", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-216", name: "PH 216", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-217", name: "PH 217", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-218", name: "PH 218", floor: 2, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-NC-02", name: "Phòng Nghiên Cứu 2", floor: 2, room_type: "office", capacity: 45, area: 160 },
  { code: "A1-213", name: "PH 213", floor: 2, room_type: "office", capacity: 50, area: 65 },
  { code: "A1-214", name: "PH 214", floor: 2, room_type: "office", capacity: 50, area: 65 },
  { code: "A1-WC-NAM-T2", name: "NVS Nam", floor: 2, room_type: "warehouse", capacity: 0, area: 25 },
  { code: "A1-301", name: "PH 301", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-302", name: "PH 302", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-303", name: "PH 303", floor: 3, room_type: "lab", capacity: 60, area: 75 },
  { code: "A1-307", name: "PH 307", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-308", name: "PH 308", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-NC-T3", name: "Phòng Nghiên Cứu 1", floor: 3, room_type: "office", capacity: 45, area: 160 },
  { code: "A1-309", name: "PH 309", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-310", name: "PH 310", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-311", name: "PH 311", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-312", name: "PH 312", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-WC-NU-T3", name: "NVS Nữ", floor: 3, room_type: "warehouse", capacity: 0, area: 25 },
  { code: "A1-304", name: "PH 304", floor: 3, room_type: "lab", capacity: 60, area: 75 },
  { code: "A1-305", name: "PH 305", floor: 3, room_type: "office", capacity: 50, area: 65 },
  { code: "A1-306", name: "PH 306", floor: 3, room_type: "office", capacity: 50, area: 65 },
  { code: "A1-315", name: "PH 315", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-316", name: "PH 316", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-YT-T3", name: "Phòng Y Tế", floor: 3, room_type: "warehouse", capacity: 15, area: 78 },
  { code: "A1-319", name: "PH 319 (Phòng Học)", floor: 3, room_type: "lecture", capacity: 45, area: 78 },
  { code: "A1-317", name: "PH 317", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-318", name: "PH 318", floor: 3, room_type: "lecture", capacity: 50, area: 65 },
  { code: "A1-313", name: "PH 313", floor: 3, room_type: "office", capacity: 50, area: 65 },
  { code: "A1-314", name: "PH 314", floor: 3, room_type: "office", capacity: 50, area: 65 },
  { code: "A1-WC-NAM-T3", name: "NVS Nam", floor: 3, room_type: "warehouse", capacity: 0, area: 25 },
  { code: "A1-VP-CNTT", name: "VP Khoa CNTT", floor: 4, room_type: "office", capacity: 0, area: 60 },
  { code: "A1-VP-KT", name: "VP Khoa Kinh tế", floor: 4, room_type: "office", capacity: 0, area: 60 },
  { code: "A1-VP-NN", name: "VP Khoa Ngoại ngữ", floor: 4, room_type: "office", capacity: 0, area: 60 },
  { code: "A1-PĐT", name: "Phòng Đào tạo", floor: 4, room_type: "office", capacity: 0, area: 75 },
  { code: "A1-PTV-T4", name: "Phòng Tài vụ", floor: 4, room_type: "office", capacity: 0, area: 55 },
  { code: "A1-WC-T4", name: "Khu vệ sinh", floor: 4, room_type: "warehouse", capacity: 0, area: 40 },
  { code: "A1-PHK", name: "Phòng họp Khoa", floor: 4, room_type: "office", capacity: 15, area: 40 },
  { code: "A1-PHT", name: "Phòng hội thảo", floor: 4, room_type: "lecture", capacity: 100, area: 140 },
  { code: "A1-401", name: "Phòng học 401", floor: 4, room_type: "lecture", capacity: 60, area: 75 },
  { code: "A1-402", name: "Phòng học 402", floor: 4, room_type: "lecture", capacity: 60, area: 75 },
  { code: "A1-TSV", name: "Tiếp sinh viên", floor: 4, room_type: "office", capacity: 0, area: 35 },
  { code: "A1-HTL", name: "Hội trường lớn", floor: 5, room_type: "lecture", capacity: 300, area: 360 },
  { code: "A1-ĐN1", name: "Phòng đa năng 1", floor: 5, room_type: "lecture", capacity: 80, area: 100 },
  { code: "A1-ĐN2", name: "Phòng đa năng 2", floor: 5, room_type: "lecture", capacity: 60, area: 80 },
  { code: "A1-STUDIO", name: "Studio thu âm", floor: 5, room_type: "lecture", capacity: 10, area: 35 },
  { code: "A1-WC-T5", name: "Khu vệ sinh", floor: 5, room_type: "warehouse", capacity: 0, area: 40 },
  { code: "A1-GYM", name: "Gym & Thể chất", floor: 5, room_type: "lecture", capacity: 25, area: 75 },
  { code: "A1-CLB-HT", name: "CLB Học thuật", floor: 5, room_type: "lecture", capacity: 30, area: 45 },
  { code: "A1-CLB-VN", name: "CLB Văn nghệ", floor: 5, room_type: "lecture", capacity: 30, area: 45 },
  { code: "A1-ĐOÀN", name: "Phòng Đoàn – Hội", floor: 5, room_type: "office", capacity: 0, area: 40 },
  { code: "A1-ST", name: "Sân thượng", floor: 5, room_type: "warehouse", capacity: 0, area: 120 }
];
